import type { ThemeDefinition } from '$lib/types';

export const aquarium: ThemeDefinition = {
  id: 'aquarium',
  name: 'Deep Aquarium',
  description: 'An underwater ecosystem',
  allowedWeather: ['clear', 'bubbles'],
  defaultWeather: 'bubbles',
  companions: ['jellyfish', 'fish', 'turtle', 'penguin'],
  defaultCompanion: 'jellyfish',
  clock: { font: 'Space Mono', shadow: '0 4px 25px rgba(33, 150, 243, 0.6)' },
  ambient: [],
  colors: {
    morning: {
      bgTop: '#81d4fa',
      bgBottom: '#0277bd',
      text: '#ffffff',
      textMuted: '#b3e5fc',
      accent: '#00b0ff',
      glass: 'rgba(2, 119, 189, 0.4)',
    },
    day: {
      bgTop: '#29b6f6',
      bgBottom: '#01579b',
      text: '#ffffff',
      textMuted: '#81d4fa',
      accent: '#00b0ff',
      glass: 'rgba(1, 87, 155, 0.4)',
    },
    sunset: {
      bgTop: '#ce93d8',
      bgBottom: '#1565c0',
      text: '#ffffff',
      textMuted: '#e1bee7',
      accent: '#b388ff',
      glass: 'rgba(21, 101, 192, 0.4)',
    },
    night: {
      bgTop: '#08111e',
      bgBottom: '#0d2b4f',
      text: '#e3f2fd',
      textMuted: '#90caf9',
      accent: '#2196f3',
      glass: 'rgba(15, 28, 46, 0.4)',
    },
    'late-night': {
      bgTop: '#03070d',
      bgBottom: '#06172e',
      text: '#bbdefb',
      textMuted: '#64b5f6',
      accent: '#1976d2',
      glass: 'rgba(6, 23, 46, 0.6)',
    },
  },
  stage: {
    minX: 0.34,
    maxX: 0.88,
    medium: 'water',
    zones: [
      {
        id: 'seaweed',
        label: 'Seaweed',
        kind: 'interact',
        x: 0.36,
        depth: 0.2,
        activity: 'play',
        stay: [5, 10],
        altitude: 0.15,
      },
      {
        id: 'rock',
        label: 'Rock ledge',
        kind: 'shelter',
        x: 0.76,
        depth: 0.3,
        activity: 'sleep',
        stay: [12, 25],
        altitude: 0.1,
      },
      {
        id: 'open-water',
        label: 'Open water',
        kind: 'rest',
        x: 0.58,
        depth: 0.6,
        activity: 'idle',
        stay: [6, 12],
        altitude: 0.85,
      },
    ],
  },
};
